[2023-01-24T17:54:16.069+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: easy.write_flights manual__2023-01-24T17:54:13.531550+00:00 [queued]>
[2023-01-24T17:54:16.075+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: easy.write_flights manual__2023-01-24T17:54:13.531550+00:00 [queued]>
[2023-01-24T17:54:16.076+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:54:16.076+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-24T17:54:16.077+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-24T17:54:16.086+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): write_flights> on 2023-01-24 17:54:13.531550+00:00
[2023-01-24T17:54:16.090+0000] {standard_task_runner.py:55} INFO - Started process 8242 to run task
[2023-01-24T17:54:16.093+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'easy', 'write_flights', 'manual__2023-01-24T17:54:13.531550+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/assignment_easy.py', '--cfg-path', '/tmp/tmpq64vca9d']
[2023-01-24T17:54:16.094+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask write_flights
[2023-01-24T17:54:16.149+0000] {task_command.py:388} INFO - Running <TaskInstance: easy.write_flights manual__2023-01-24T17:54:13.531550+00:00 [running]> on host 2ee7bc173f76
[2023-01-24T17:54:16.222+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=easy
AIRFLOW_CTX_TASK_ID=write_flights
AIRFLOW_CTX_EXECUTION_DATE=2023-01-24T17:54:13.531550+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-24T17:54:13.531550+00:00
[2023-01-24T17:54:16.226+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment_easy.py", line 46, in write_flights
    f.write(data['flights'])
TypeError: write() argument must be str, not list
[2023-01-24T17:54:16.235+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=easy, task_id=write_flights, execution_date=20230124T175413, start_date=20230124T175416, end_date=20230124T175416
[2023-01-24T17:54:16.242+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task write_flights (write() argument must be str, not list; 8242)
[2023-01-24T17:54:16.265+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-24T17:54:16.281+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
